### ISSUE TITLE
Google Maps location is null?

### ISSUE THREAD

**Issue by gpgreenleaf** [rgreen1207/FishOps#10]
I'm not sure if the logcat message below is directly related to why my version of this app starts in Africa with no apparent pin-marker, but it definitely has to be resolved! Especially if this is how the judges are going to see it when the compile it on their devices. :worried:

> I/j: location is null

![fishopsmapsnulllocation](https://cloud.githubusercontent.com/assets/2936762/14802918/c099426c-0b09-11e6-8263-4a76dd799062.JPG)

**Comment by gpgreenleaf** [comment]
Zac, this error might be because I'm running on an emulator, but could you please run it on your phone just in case? I will also look into it more, but I just don't want the judges to get a non-working copy of the code. Thanks, man.

/cc @yellowbullet100

**Comment by gpgreenleaf** [comment]
Also, the button in the top-right that is supposed to snap the display to the center of where the pin-marker is does not work, which to me signifies that the maps feature is broken right now.

**Comment by yellowbullet100** [comment]
The marker still appears on my phone. But you're right, when I run it on the emulator the marker does not appear. What to you suggest we do?

**Comment by gpgreenleaf** [comment]
I'm researching it now. I think it might have something to do with issue #3 with the missing services. I'm guessing maybe an API key mismatch, but I'll let you know what I find.

**Comment by yellowbullet100** [comment]
What if I set the marker to Manila if the phones location is null?

**Comment by gpgreenleaf** [comment]
Yeah, that sounds good. At least then I'll know exactly where to scroll to in order to check if the marker is even working.
